/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.ignite.testsuites;

import junit.framework.TestSuite;
import org.apache.ignite.cache.affinity.rendezvous.RendezvousAffinityFunctionSelfTest;
import org.apache.ignite.cache.store.CacheStoreSessionListenerLifecycleSelfTest;
import org.apache.ignite.igfs.IgfsPathSelfTest;
import org.apache.ignite.internal.ClusterMetricsSelfTest;
import org.apache.ignite.internal.GridAffinityMappedTest;
import org.apache.ignite.internal.GridAffinityP2PSelfTest;
import org.apache.ignite.internal.GridGetOrStartSelfTest;
import org.apache.ignite.internal.GridStartupTest;
import org.apache.ignite.internal.GridTaskExecutionContextSelfTest;
import org.apache.ignite.internal.IgniteInternalCacheRemoveTest;
import org.apache.ignite.internal.binary.BinaryFieldExtractionSelfTest;
import org.apache.ignite.internal.managers.GridManagerMxBeanIllegalArgumentHandleTest;
import org.apache.ignite.internal.managers.communication.GridIoManagerSelfTest;
import org.apache.ignite.internal.pagemem.impl.PageMemoryNoLoadSelfTest;
import org.apache.ignite.internal.processors.cache.CacheAtomicSingleMessageCountSelfTest;
import org.apache.ignite.internal.processors.cache.GridCacheAtomicUsersAffinityMapperSelfTest;
import org.apache.ignite.internal.processors.cache.GridCacheClearLocallySelfTest;
import org.apache.ignite.internal.processors.cache.GridCacheConcurrentGetCacheOnClientTest;
import org.apache.ignite.internal.processors.cache.GridCacheConcurrentTxMultiNodeTest;
import org.apache.ignite.internal.processors.cache.GridCacheFullTextQueryMultithreadedSelfTest;
import org.apache.ignite.internal.processors.cache.GridCacheIteratorPerformanceTest;
import org.apache.ignite.internal.processors.cache.GridCacheKeyCheckNearEnabledSelfTest;
import org.apache.ignite.internal.processors.cache.GridCacheKeyCheckSelfTest;
import org.apache.ignite.internal.processors.cache.GridCacheLeakTest;
import org.apache.ignite.internal.processors.cache.GridCacheMultiUpdateLockSelfTest;
import org.apache.ignite.internal.processors.cache.GridCacheMvccFlagsTest;
import org.apache.ignite.internal.processors.cache.GridCacheReplicatedUsersAffinityMapperSelfTest;
import org.apache.ignite.internal.processors.cache.GridCacheReturnValueTransferSelfTest;
import org.apache.ignite.internal.processors.cache.GridCacheSlowTxWarnTest;
import org.apache.ignite.internal.processors.cache.GridCacheTtlManagerLoadTest;
import org.apache.ignite.internal.processors.cache.GridCacheTxUsersAffinityMapperSelfTest;
import org.apache.ignite.internal.processors.cache.IgniteCacheBinaryEntryProcessorSelfTest;
import org.apache.ignite.internal.processors.cache.IgniteCacheObjectPutSelfTest;
import org.apache.ignite.internal.processors.cache.IgniteCacheSerializationSelfTest;
import org.apache.ignite.internal.processors.cache.IgniteCacheStartStopLoadTest;
import org.apache.ignite.internal.processors.cache.IgniteCachingProviderSelfTest;
import org.apache.ignite.internal.processors.cache.IgniteOnePhaseCommitNearSelfTest;
import org.apache.ignite.internal.processors.cache.IgniteStaticCacheStartSelfTest;
import org.apache.ignite.internal.processors.cache.InterceptorWithKeepBinaryCacheFullApiTest;
import org.apache.ignite.internal.processors.cache.binary.distributed.dht.GridCacheBinaryObjectsAtomicNearDisabledOnheapSelfTest;
import org.apache.ignite.internal.processors.cache.binary.distributed.dht.GridCacheBinaryObjectsAtomicOnheapSelfTest;
import org.apache.ignite.internal.processors.cache.binary.distributed.dht.GridCacheBinaryObjectsPartitionedNearDisabledOnheapSelfTest;
import org.apache.ignite.internal.processors.cache.binary.distributed.dht.GridCacheBinaryObjectsPartitionedOnheapSelfTest;
import org.apache.ignite.internal.processors.cache.binary.local.GridCacheBinaryObjectsLocalOnheapSelfTest;
import org.apache.ignite.internal.processors.cache.datastructures.IgniteDataStructuresNoClassOnServerTest;
import org.apache.ignite.internal.processors.cache.datastructures.partitioned.GridCachePartitionedAtomicReferenceMultiNodeTest;
import org.apache.ignite.internal.processors.cache.datastructures.replicated.GridCacheReplicatedAtomicReferenceMultiNodeTest;
import org.apache.ignite.internal.processors.cache.distributed.CacheClientsConcurrentStartTest;
import org.apache.ignite.internal.processors.cache.distributed.CacheTryLockMultithreadedTest;
import org.apache.ignite.internal.processors.cache.distributed.IgniteCacheClientMultiNodeUpdateTopologyLockTest;
import org.apache.ignite.internal.processors.cache.distributed.dht.GridCacheColocatedDebugTest;
import org.apache.ignite.internal.processors.cache.distributed.dht.GridCacheDhtAtomicEvictionNearReadersSelfTest;
import org.apache.ignite.internal.processors.cache.distributed.dht.GridCacheDhtEntrySetSelfTest;
import org.apache.ignite.internal.processors.cache.distributed.dht.GridCacheDhtEvictionNearReadersSelfTest;
import org.apache.ignite.internal.processors.cache.distributed.dht.GridCacheDhtMultiBackupTest;
import org.apache.ignite.internal.processors.cache.distributed.dht.GridCacheDhtPreloadMessageCountTest;
import org.apache.ignite.internal.processors.cache.distributed.dht.GridCacheDhtPreloadPerformanceTest;
import org.apache.ignite.internal.processors.cache.distributed.dht.GridCachePartitionedNearDisabledMetricsSelfTest;
import org.apache.ignite.internal.processors.cache.distributed.dht.IgniteCacheContainsKeyColocatedSelfTest;
import org.apache.ignite.internal.processors.cache.distributed.dht.IgniteCrossCacheTxNearEnabledSelfTest;
import org.apache.ignite.internal.processors.cache.distributed.dht.IgniteTxConsistencyColocatedRestartSelfTest;
import org.apache.ignite.internal.processors.cache.distributed.dht.atomic.GridCacheAtomicPreloadSelfTest;
import org.apache.ignite.internal.processors.cache.distributed.dht.atomic.IgniteCacheContainsKeyColocatedAtomicSelfTest;
import org.apache.ignite.internal.processors.cache.distributed.dht.atomic.IgniteCacheContainsKeyNearAtomicSelfTest;
import org.apache.ignite.internal.processors.cache.distributed.near.GridCachePartitionedAffinityExcludeNeighborsPerformanceTest;
import org.apache.ignite.internal.processors.cache.distributed.near.GridCachePartitionedEntryLockSelfTest;
import org.apache.ignite.internal.processors.cache.distributed.near.GridCachePartitionedEvictionSelfTest;
import org.apache.ignite.internal.processors.cache.distributed.near.GridCachePartitionedNestedTxTest;
import org.apache.ignite.internal.processors.cache.distributed.near.GridCachePartitionedStorePutSelfTest;
import org.apache.ignite.internal.processors.cache.distributed.near.GridCachePartitionedTxConcurrentGetTest;
import org.apache.ignite.internal.processors.cache.distributed.near.GridCachePartitionedTxMultiNodeSelfTest;
import org.apache.ignite.internal.processors.cache.distributed.near.GridCachePartitionedTxReadTest;
import org.apache.ignite.internal.processors.cache.distributed.near.IgniteCacheContainsKeyNearSelfTest;
import org.apache.ignite.internal.processors.cache.distributed.near.IgniteCacheNearTxRollbackTest;
import org.apache.ignite.internal.processors.cache.distributed.near.NearCacheMultithreadedUpdateTest;
import org.apache.ignite.internal.processors.cache.distributed.near.NearCachePutAllMultinodeTest;
import org.apache.ignite.internal.processors.cache.distributed.rebalancing.GridCacheRebalancingOrderingTest;
import org.apache.ignite.internal.processors.cache.distributed.replicated.GridCacheReplicatedEntrySetSelfTest;
import org.apache.ignite.internal.processors.cache.distributed.replicated.GridCacheReplicatedMarshallerTxTest;
import org.apache.ignite.internal.processors.cache.distributed.replicated.GridCacheReplicatedOnheapFullApiSelfTest;
import org.apache.ignite.internal.processors.cache.distributed.replicated.GridCacheReplicatedOnheapMultiNodeFullApiSelfTest;
import org.apache.ignite.internal.processors.cache.distributed.replicated.GridCacheReplicatedTxConcurrentGetTest;
import org.apache.ignite.internal.processors.cache.distributed.replicated.GridCacheReplicatedTxMultiNodeBasicTest;
import org.apache.ignite.internal.processors.cache.distributed.replicated.GridCacheReplicatedTxReadTest;
import org.apache.ignite.internal.processors.cache.eviction.sorted.SortedEvictionPolicyPerformanceTest;
import org.apache.ignite.internal.processors.cache.expiry.IgniteCacheAtomicLocalOnheapExpiryPolicyTest;
import org.apache.ignite.internal.processors.cache.expiry.IgniteCacheAtomicOnheapExpiryPolicyTest;
import org.apache.ignite.internal.processors.cache.local.GridCacheLocalBasicStoreMultithreadedSelfTest;
import org.apache.ignite.internal.processors.cache.local.GridCacheLocalTxReadTest;
import org.apache.ignite.internal.processors.cache.persistence.IgnitePdsRemoveDuringRebalancingTest;
import org.apache.ignite.internal.processors.cache.persistence.IgnitePersistenceSequentialCheckpointTest;
import org.apache.ignite.internal.processors.cache.persistence.baseline.IgniteStableBaselineCachePutAllFailoverTest;
import org.apache.ignite.internal.processors.cache.persistence.baseline.IgniteStableBaselineCacheRemoveFailoverTest;
import org.apache.ignite.internal.processors.cache.persistence.db.file.IgnitePdsCheckpointSimpleTest;
import org.apache.ignite.internal.processors.cache.persistence.db.wal.IgniteWalRecoverySeveralRestartsTest;
import org.apache.ignite.internal.processors.cache.persistence.file.FileDownloaderTest;
import org.apache.ignite.internal.processors.cache.persistence.pagemem.FullPageIdTableTest;
import org.apache.ignite.internal.processors.cache.persistence.pagemem.PageIdDistributionTest;
import org.apache.ignite.internal.processors.cache.persistence.pagemem.PagesWriteThrottleSandboxTest;
import org.apache.ignite.internal.processors.cache.persistence.standbycluster.extended.GridActivateExtensionTest;
import org.apache.ignite.internal.processors.cache.persistence.tree.io.TrackingPageIOTest;
import org.apache.ignite.internal.processors.cache.query.GridCircularQueueTest;
import org.apache.ignite.internal.processors.cache.query.IndexingSpiQueryWithH2IndexingSelfTest;
import org.apache.ignite.internal.processors.cache.query.continuous.CacheContinuousQueryCounterPartitionedAtomicTest;
import org.apache.ignite.internal.processors.cache.query.continuous.CacheContinuousQueryCounterPartitionedTxTest;
import org.apache.ignite.internal.processors.cache.query.continuous.CacheContinuousQueryCounterReplicatedAtomicTest;
import org.apache.ignite.internal.processors.cache.query.continuous.CacheContinuousQueryCounterReplicatedTxTest;
import org.apache.ignite.internal.processors.cache.query.continuous.CacheContinuousQueryFailoverAtomicNearEnabledSelfSelfTest;
import org.apache.ignite.internal.processors.cache.query.continuous.IgniteCacheContinuousQueryReconnectTest;
import org.apache.ignite.internal.processors.cache.transactions.TxDeadlockCauseTest;
import org.apache.ignite.internal.processors.compute.GridComputeJobExecutionErrorToLogManualTest;
import org.apache.ignite.internal.processors.datastreamer.IgniteDataStreamerPerformanceTest;
import org.apache.ignite.internal.processors.service.GridServiceDeploymentExceptionPropagationTest;
import org.apache.ignite.internal.processors.service.IgniteServiceDeployment2ClassLoadersOptimizedMarshallerTest;
import org.apache.ignite.internal.processors.service.IgniteServiceDeploymentClassLoadingOptimizedMarshallerTest;
import org.apache.ignite.internal.util.IgniteDevOnlyLogTest;
import org.apache.ignite.internal.util.nio.GridRoundTripTest;
import org.apache.ignite.internal.util.offheap.unsafe.GridUnsafeMapPerformanceTest;
import org.apache.ignite.internal.util.offheap.unsafe.GridUnsafePartitionedMapPerformanceTest;
import org.apache.ignite.internal.util.tostring.IncludeSensitiveAtomicTest;
import org.apache.ignite.internal.util.tostring.IncludeSensitiveTransactionalTest;
import org.apache.ignite.jvmtest.FileIOTest;
import org.apache.ignite.jvmtest.FileLocksTest;
import org.apache.ignite.jvmtest.LinkedHashMapTest;
import org.apache.ignite.jvmtest.NetworkFailureTest;
import org.apache.ignite.jvmtest.QueueSizeCounterMultiThreadedTest;
import org.apache.ignite.jvmtest.ReadWriteLockMultiThreadedTest;
import org.apache.ignite.jvmtest.RegExpTest;
import org.apache.ignite.jvmtest.ServerSocketMultiThreadedTest;
import org.apache.ignite.lang.GridFuncPerformanceTest;
import org.apache.ignite.lang.GridMetadataAwareAdapterLoadSelfTest;
import org.apache.ignite.lang.utils.GridCircularBufferPerformanceTest;
import org.apache.ignite.lang.utils.GridConcurrentHashMapSelfTest;
import org.apache.ignite.lang.utils.GridLeanMapPerformanceTest;
import org.apache.ignite.lang.utils.IgniteOffheapReadWriteLockSelfTest;
import org.apache.ignite.loadtests.GridCacheMultiNodeLoadTest;
import org.apache.ignite.loadtests.cache.GridCacheWriteBehindStoreLoadTest;
import org.apache.ignite.loadtests.datastructures.GridCachePartitionedAtomicLongLoadTest;
import org.apache.ignite.loadtests.direct.multisplit.GridMultiSplitsLoadTest;
import org.apache.ignite.loadtests.direct.multisplit.GridMultiSplitsRedeployLoadTest;
import org.apache.ignite.loadtests.direct.newnodes.GridSingleSplitsNewNodesMulticastLoadTest;
import org.apache.ignite.loadtests.direct.redeploy.GridSingleSplitsRedeployLoadTest;
import org.apache.ignite.loadtests.direct.session.GridSessionLoadTest;
import org.apache.ignite.loadtests.direct.stealing.GridStealingLoadTest;
import org.apache.ignite.loadtests.hashmap.GridHashMapLoadTest;
import org.apache.ignite.marshaller.GridMarshallerPerformanceTest;
import org.apache.ignite.p2p.GridP2PTestTaskExecutionTest;
import org.apache.ignite.spi.checkpoint.sharedfs.GridSharedFsCheckpointSpiMultiThreadedSelfTest;
import org.apache.ignite.spi.communication.tcp.GridCacheDhtLockBackupSelfTest;
import org.apache.ignite.spi.communication.tcp.GridTcpCommunicationSpiLanTest;
import org.apache.ignite.spi.discovery.tcp.TcpDiscoveryConcurrentStartTest;
import org.apache.ignite.spi.discovery.tcp.TcpDiscoverySpiRandomStartStopTest;
import org.apache.ignite.spi.discovery.tcp.TcpDiscoverySpiSslSelfTest;
import org.apache.ignite.spi.discovery.tcp.TcpDiscoverySpiWildcardSelfTest;
import org.apache.ignite.startup.cmdline.GridCommandLineLoaderTest;
import org.apache.ignite.startup.servlet.GridServletLoaderTest;
import org.apache.ignite.thread.GridThreadTest;
import org.apache.ignite.util.GridConcurrentLinkedDequeMultiThreadedTest;
import org.apache.ignite.util.GridIndexFillTest;
import org.apache.ignite.util.GridLogThrottleTest;
import org.apache.ignite.util.GridRandomSelfTest;
import org.apache.ignite.util.GridSnapshotLockSelfTest;
import org.apache.ignite.util.GridTopologyHeapSizeSelfTest;
import org.apache.ignite.util.GridTransientTest;

/**
 * Tests suite for orphaned tests.
 */
public class IgniteLostAndFoundTestSuite extends TestSuite {
    /**
     * @return Tests suite for orphaned tests (not in any test sute previously).
     */
    public static TestSuite suite() {
        TestSuite suite = new TestSuite("Ignite List And Found Test Suite");

        suite.addTestSuite(BinaryFieldExtractionSelfTest.class);
        suite.addTestSuite(CacheAtomicSingleMessageCountSelfTest.class);
        suite.addTestSuite(CacheClientsConcurrentStartTest.class);
        suite.addTestSuite(CacheContinuousQueryCounterPartitionedAtomicTest.class);
        suite.addTestSuite(CacheContinuousQueryCounterPartitionedTxTest.class);
        suite.addTestSuite(CacheContinuousQueryCounterReplicatedAtomicTest.class);
        suite.addTestSuite(CacheContinuousQueryCounterReplicatedTxTest.class);
        suite.addTestSuite(CacheContinuousQueryFailoverAtomicNearEnabledSelfSelfTest.class);
        suite.addTestSuite(CacheStoreSessionListenerLifecycleSelfTest.class);
        suite.addTestSuite(CacheTryLockMultithreadedTest.class);
        suite.addTestSuite(ClusterMetricsSelfTest.class);
        suite.addTestSuite(FileDownloaderTest.class);
        suite.addTestSuite(FileIOTest.class);
        suite.addTestSuite(FileLocksTest.class);
        suite.addTestSuite(FullPageIdTableTest.class);
        suite.addTestSuite(GridActivateExtensionTest.class);
        suite.addTestSuite(GridAffinityMappedTest.class);
        suite.addTestSuite(GridAffinityP2PSelfTest.class);
        suite.addTestSuite(GridCacheAtomicPreloadSelfTest.class);
        suite.addTestSuite(GridCacheAtomicUsersAffinityMapperSelfTest.class);
        suite.addTestSuite(GridCacheBinaryObjectsAtomicNearDisabledOnheapSelfTest.class);
        suite.addTestSuite(GridCacheBinaryObjectsAtomicOnheapSelfTest.class);
        suite.addTestSuite(GridCacheBinaryObjectsLocalOnheapSelfTest.class);
        suite.addTestSuite(GridCacheBinaryObjectsPartitionedNearDisabledOnheapSelfTest.class);
        suite.addTestSuite(GridCacheBinaryObjectsPartitionedOnheapSelfTest.class);
        suite.addTestSuite(GridCacheClearLocallySelfTest.class);
        suite.addTestSuite(GridCacheColocatedDebugTest.class);
        suite.addTestSuite(GridCacheConcurrentGetCacheOnClientTest.class);
        suite.addTestSuite(GridCacheConcurrentTxMultiNodeTest.class);
        suite.addTestSuite(GridCacheDhtAtomicEvictionNearReadersSelfTest.class);
        suite.addTestSuite(GridCacheDhtEntrySetSelfTest.class);
        suite.addTestSuite(GridCacheDhtEvictionNearReadersSelfTest.class);
        suite.addTestSuite(GridCacheDhtLockBackupSelfTest.class);
        suite.addTestSuite(GridCacheDhtMultiBackupTest.class);
        suite.addTestSuite(GridCacheDhtPreloadMessageCountTest.class);
        suite.addTestSuite(GridCacheDhtPreloadPerformanceTest.class);
        suite.addTestSuite(GridCacheFullTextQueryMultithreadedSelfTest.class);
        suite.addTestSuite(GridCacheIteratorPerformanceTest.class);
        suite.addTestSuite(GridCacheKeyCheckNearEnabledSelfTest.class);
        suite.addTestSuite(GridCacheKeyCheckSelfTest.class);
        suite.addTestSuite(GridCacheLeakTest.class);
        suite.addTestSuite(GridCacheLocalBasicStoreMultithreadedSelfTest.class);
        suite.addTestSuite(GridCacheLocalTxReadTest.class);
        suite.addTestSuite(GridCacheMultiNodeLoadTest.class);
        suite.addTestSuite(GridCacheMultiUpdateLockSelfTest.class);
        suite.addTestSuite(GridCacheMvccFlagsTest.class);
        suite.addTestSuite(GridCachePartitionedAffinityExcludeNeighborsPerformanceTest.class);
        suite.addTestSuite(GridCachePartitionedAtomicLongLoadTest.class);
        suite.addTestSuite(GridCachePartitionedAtomicReferenceMultiNodeTest.class);
        suite.addTestSuite(GridCachePartitionedEntryLockSelfTest.class);
        suite.addTestSuite(GridCachePartitionedEvictionSelfTest.class);
        suite.addTestSuite(GridCachePartitionedNearDisabledMetricsSelfTest.class);
        suite.addTestSuite(GridCachePartitionedNestedTxTest.class);
        suite.addTestSuite(GridCachePartitionedStorePutSelfTest.class);
        suite.addTestSuite(GridCachePartitionedTxConcurrentGetTest.class);
        suite.addTestSuite(GridCachePartitionedTxMultiNodeSelfTest.class);
        suite.addTestSuite(GridCachePartitionedTxReadTest.class);
        suite.addTestSuite(GridCacheRebalancingOrderingTest.class);
        suite.addTestSuite(GridCacheReplicatedAtomicReferenceMultiNodeTest.class);
        suite.addTestSuite(GridCacheReplicatedEntrySetSelfTest.class);
        suite.addTestSuite(GridCacheReplicatedMarshallerTxTest.class);
        suite.addTestSuite(GridCacheReplicatedOnheapFullApiSelfTest.class);
        suite.addTestSuite(GridCacheReplicatedOnheapMultiNodeFullApiSelfTest.class);
        suite.addTestSuite(GridCacheReplicatedTxConcurrentGetTest.class);
        suite.addTestSuite(GridCacheReplicatedTxMultiNodeBasicTest.class);
        suite.addTestSuite(GridCacheReplicatedTxReadTest.class);
        suite.addTestSuite(GridCacheReplicatedUsersAffinityMapperSelfTest.class);
        suite.addTestSuite(GridCacheReturnValueTransferSelfTest.class);
        suite.addTestSuite(GridCacheSlowTxWarnTest.class);
        suite.addTestSuite(GridCacheTtlManagerLoadTest.class);
        suite.addTestSuite(GridCacheTxUsersAffinityMapperSelfTest.class);
        suite.addTestSuite(GridCacheWriteBehindStoreLoadTest.class);
        suite.addTestSuite(GridCircularBufferPerformanceTest.class);
        suite.addTestSuite(GridCircularQueueTest.class);
        suite.addTestSuite(GridCommandLineLoaderTest.class);
        suite.addTestSuite(GridComputeJobExecutionErrorToLogManualTest.class);
        suite.addTestSuite(GridConcurrentHashMapSelfTest.class);
        suite.addTestSuite(GridConcurrentLinkedDequeMultiThreadedTest.class);
        suite.addTestSuite(GridFuncPerformanceTest.class);
        suite.addTestSuite(GridGetOrStartSelfTest.class);
        suite.addTestSuite(GridHashMapLoadTest.class);
        suite.addTestSuite(GridIndexFillTest.class);
        suite.addTestSuite(GridIoManagerSelfTest.class);
        suite.addTestSuite(GridLeanMapPerformanceTest.class);
        suite.addTestSuite(GridLogThrottleTest.class);
        suite.addTestSuite(GridManagerMxBeanIllegalArgumentHandleTest.class);
        suite.addTestSuite(GridMarshallerPerformanceTest.class);
        suite.addTestSuite(GridMetadataAwareAdapterLoadSelfTest.class);
        suite.addTestSuite(GridMultiSplitsLoadTest.class);
        suite.addTestSuite(GridMultiSplitsRedeployLoadTest.class);
        suite.addTestSuite(GridP2PTestTaskExecutionTest.class);
        suite.addTestSuite(GridRandomSelfTest.class);
        suite.addTestSuite(GridRoundTripTest.class);
        suite.addTestSuite(GridServiceDeploymentExceptionPropagationTest.class);
        suite.addTestSuite(GridServletLoaderTest.class);
        suite.addTestSuite(GridSessionLoadTest.class);
        suite.addTestSuite(GridSharedFsCheckpointSpiMultiThreadedSelfTest.class);
        suite.addTestSuite(GridSingleSplitsNewNodesMulticastLoadTest.class);
        suite.addTestSuite(GridSingleSplitsRedeployLoadTest.class);
        suite.addTestSuite(GridSnapshotLockSelfTest.class);
        suite.addTestSuite(GridStartupTest.class);
        suite.addTestSuite(GridStealingLoadTest.class);
        suite.addTestSuite(GridTaskExecutionContextSelfTest.class);
        suite.addTestSuite(GridTcpCommunicationSpiLanTest.class);
        suite.addTestSuite(GridThreadTest.class);
        suite.addTestSuite(GridTopologyHeapSizeSelfTest.class);
        suite.addTestSuite(GridTransientTest.class);
        suite.addTestSuite(GridUnsafeMapPerformanceTest.class);
        suite.addTestSuite(GridUnsafePartitionedMapPerformanceTest.class);
        suite.addTestSuite(IgfsPathSelfTest.class);
        suite.addTestSuite(IgniteCacheAtomicLocalOnheapExpiryPolicyTest.class);
        suite.addTestSuite(IgniteCacheAtomicOnheapExpiryPolicyTest.class);
        suite.addTestSuite(IgniteCacheBinaryEntryProcessorSelfTest.class);
        suite.addTestSuite(IgniteCacheClientMultiNodeUpdateTopologyLockTest.class);
        suite.addTestSuite(IgniteCacheContainsKeyColocatedAtomicSelfTest.class);
        suite.addTestSuite(IgniteCacheContainsKeyColocatedSelfTest.class);
        suite.addTestSuite(IgniteCacheContainsKeyNearAtomicSelfTest.class);
        suite.addTestSuite(IgniteCacheContainsKeyNearSelfTest.class);
        suite.addTestSuite(IgniteCacheContinuousQueryReconnectTest.class);
        suite.addTestSuite(IgniteCacheNearTxRollbackTest.class);
        suite.addTestSuite(IgniteCacheObjectPutSelfTest.class);
        suite.addTestSuite(IgniteCacheSerializationSelfTest.class);
        suite.addTestSuite(IgniteCacheStartStopLoadTest.class);
        suite.addTestSuite(IgniteCachingProviderSelfTest.class);
        suite.addTestSuite(IgniteCrossCacheTxNearEnabledSelfTest.class);
        suite.addTestSuite(IgniteDataStreamerPerformanceTest.class);
        suite.addTestSuite(IgniteDataStructuresNoClassOnServerTest.class);
        suite.addTestSuite(IgniteDevOnlyLogTest.class);
        suite.addTestSuite(IgniteInternalCacheRemoveTest.class);
        suite.addTestSuite(IgniteOffheapReadWriteLockSelfTest.class);
        suite.addTestSuite(IgniteOnePhaseCommitNearSelfTest.class);
        suite.addTestSuite(IgnitePdsCheckpointSimpleTest.class);
        suite.addTestSuite(IgnitePdsRemoveDuringRebalancingTest.class);
        suite.addTestSuite(IgnitePersistenceSequentialCheckpointTest.class);
        suite.addTestSuite(IgniteServiceDeployment2ClassLoadersOptimizedMarshallerTest.class);
        suite.addTestSuite(IgniteServiceDeploymentClassLoadingOptimizedMarshallerTest.class);
        suite.addTestSuite(IgniteStableBaselineCachePutAllFailoverTest.class);
        suite.addTestSuite(IgniteStableBaselineCacheRemoveFailoverTest.class);
        suite.addTestSuite(IgniteStaticCacheStartSelfTest.class);
        suite.addTestSuite(IgniteTxConsistencyColocatedRestartSelfTest.class);
        suite.addTestSuite(IgniteWalRecoverySeveralRestartsTest.class);
        suite.addTestSuite(IncludeSensitiveAtomicTest.class);
        suite.addTestSuite(IncludeSensitiveTransactionalTest.class);
        suite.addTestSuite(IndexingSpiQueryWithH2IndexingSelfTest.class);
        suite.addTestSuite(InterceptorWithKeepBinaryCacheFullApiTest.class);
        suite.addTestSuite(LinkedHashMapTest.class);
        suite.addTestSuite(NearCacheMultithreadedUpdateTest.class);
        suite.addTestSuite(NearCachePutAllMultinodeTest.class);
        suite.addTestSuite(NetworkFailureTest.class);
        suite.addTestSuite(PageIdDistributionTest.class);
        suite.addTestSuite(PageMemoryNoLoadSelfTest.class);
        suite.addTestSuite(PagesWriteThrottleSandboxTest.class);
        suite.addTestSuite(QueueSizeCounterMultiThreadedTest.class);
        suite.addTestSuite(ReadWriteLockMultiThreadedTest.class);
        suite.addTestSuite(RegExpTest.class);
        suite.addTestSuite(RendezvousAffinityFunctionSelfTest.class);
        suite.addTestSuite(ServerSocketMultiThreadedTest.class);
        suite.addTestSuite(SortedEvictionPolicyPerformanceTest.class);
        suite.addTestSuite(TcpDiscoveryConcurrentStartTest.class);
        suite.addTestSuite(TcpDiscoverySpiRandomStartStopTest.class);
        suite.addTestSuite(TcpDiscoverySpiSslSelfTest.class);
        suite.addTestSuite(TcpDiscoverySpiWildcardSelfTest.class);
        suite.addTestSuite(TrackingPageIOTest.class);
        suite.addTestSuite(TxDeadlockCauseTest.class);

        // Main classes:
        //suite.addTestSuite(ConcurrentMapTest.class);
        //suite.addTestSuite(GridBasicPerformanceTest.class);
        //suite.addTestSuite(GridBenchmarkCacheGetLoadTest.class);
        //suite.addTestSuite(GridBoundedConcurrentLinkedHashSetLoadTest.class);
        //suite.addTestSuite(GridCacheDataStructuresLoadTest.class);
        //suite.addTestSuite(GridCacheReplicatedPreloadUndeploysTest.class);
        //suite.addTestSuite(GridCacheLoadTest.class);
        //suite.addTestSuite(GridCacheMultiNodeDataStructureTest.class);
        //suite.addTestSuite(GridCapacityLoadTest.class);
        //suite.addTestSuite(GridContinuousOperationsLoadTest.class);
        //suite.addTestSuite(GridFactoryVmShutdownTest.class);
        //suite.addTestSuite(GridFutureListenPerformanceTest.class);
        //suite.addTestSuite(GridFutureQueueTest.class);
        //suite.addTestSuite(GridGcTimeoutTest.class);
        //suite.addTestSuite(GridJobExecutionSingleNodeLoadTest.class);
        //suite.addTestSuite(GridJobExecutionSingleNodeSemaphoreLoadTest.class);
        //suite.addTestSuite(GridJobLoadTest.class);
        //suite.addTestSuite(GridMergeSortLoadTest.class);
        //suite.addTestSuite(GridNioBenchmarkTest.class);
        //suite.addTestSuite(GridThreadPriorityTest.class);
        //suite.addTestSuite(GridSystemCurrentTimeMillisTest.class);
        //suite.addTestSuite(BlockingQueueTest.class);
        //suite.addTestSuite(MultipleFileIOTest.class);
        //suite.addTestSuite(GridSingleExecutionTest.class);

        return suite;
    }
}
