export const REMOVE_CLUSTERS_LOCAL_REMOTE = 'REMOVE_CLUSTERS_LOCAL_REMOTE';
export const REMOVE_CLUSTER_ITEMS = 'REMOVE_CLUSTER_ITEMS';
export const REMOVE_CLUSTER_ITEMS_CONFIRMED = 'REMOVE_CLUSTER_ITEMS_CONFIRMED';
export const ADVANCED_SAVE_COMPLETE_CONFIGURATION = 'ADVANCED_SAVE_COMPLETE_CONFIGURATION';
