/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.ignite.yardstick.cache.model;

import java.io.*;
import org.apache.ignite.cache.query.annotations.QuerySqlField;

/**
 * Position definition.
 *
 * Code generated by Apache Ignite Schema Import utility: 07/03/2017.
 */
public class Position implements Serializable {
    /** */
    private static final long serialVersionUID = 0L;

    /** Value for posnId. */
    @QuerySqlField(index = true)
    private String posnId;

    /** Value for posnVerN. */
    @QuerySqlField
    private Long posnVerN;

    /** Value for accId. */
    @QuerySqlField
    private String accId;

    /** Value for accN. */
    @QuerySqlField
    private String accN;

    /** Value for csdnC. */
    @QuerySqlField
    private String csdnC;

    /** Value for accTyC. */
    @QuerySqlField
    private String accTyC;

    /** Value for issIdTyC. */
    @QuerySqlField
    private String issIdTyC;

    /** Value for issId. */
    @QuerySqlField
    private String issId;

    /** Value for issSrcC. */
    @QuerySqlField
    private String issSrcC;

    /** Value for issEffD. */
    @QuerySqlField
    private Integer issEffD;

    /** Value for srcN. */
    @QuerySqlField
    private String srcN;

    /** Value for srcNm. */
    @QuerySqlField
    private String srcNm;

    /** Value for plnN. */
    @QuerySqlField
    private String plnN;

    /** Value for currC. */
    @QuerySqlField
    private String currC;

    /** Value for clsPrcA. */
    @QuerySqlField
    private Double clsPrcA;

    /** Value for tdMkvlA. */
    @QuerySqlField
    private Double tdMkvlA;

    /** Value for sdMkvlA. */
    @QuerySqlField
    private Double sdMkvlA;

    /** Value for tdLngShtC. */
    @QuerySqlField
    private String tdLngShtC;

    /** Value for sdLngShtC. */
    @QuerySqlField
    private String sdLngShtC;

    /** Value for tdQtyA. */
    @QuerySqlField
    private Double tdQtyA;

    /** Value for sdQtyA. */
    @QuerySqlField
    private Double sdQtyA;

    /** Value for sfkShrQ. */
    @QuerySqlField
    private Double sfkShrQ;

    /** Value for trnfShrQ. */
    @QuerySqlField
    private Double trnfShrQ;

    /** Value for lglTrnfShrQ. */
    @QuerySqlField
    private Double lglTrnfShrQ;

    /** Value for nonNegShrQ. */
    @QuerySqlField
    private Double nonNegShrQ;

    /** Value for pldgShrQ. */
    @QuerySqlField
    private Double pldgShrQ;

    /** Value for mkvlC. */
    @QuerySqlField
    private String mkvlC;

    /** Value for loclMktPrcD. */
    @QuerySqlField
    private Integer loclMktPrcD;

    /** Value for loclPrcA. */
    @QuerySqlField
    private Double loclPrcA;

    /** Value for loclTdMkvlA. */
    @QuerySqlField
    private Double loclTdMkvlA;

    /** Value for cnvPrcA. */
    @QuerySqlField
    private Double cnvPrcA;

    /** Value for mulrDivC. */
    @QuerySqlField
    private String mulrDivC;

    /** Value for loclSdMkvlA. */
    @QuerySqlField
    private Double loclSdMkvlA;

    /** Value for ctryC. */
    @QuerySqlField
    private String ctryC;

    /** Value for asetClC. */
    @QuerySqlField
    private String asetClC;

    /** Value for clsQA. */
    @QuerySqlField
    private Double clsQA;

    /** Value for cbasA. */
    @QuerySqlField
    private Double cbasA;

    /** Value for cbasGnlsA. */
    @QuerySqlField
    private Double cbasGnlsA;

    /** Value for mkvlAcriA. */
    @QuerySqlField
    private Double mkvlAcriA;

    /** Value for portP. */
    @QuerySqlField
    private Double portP;

    /** Value for avgCostA. */
    @QuerySqlField
    private Double avgCostA;

    /** Value for ttCostA. */
    @QuerySqlField
    private Double ttCostA;

    /** Value for acruIntA. */
    @QuerySqlField
    private Double acruIntA;

    /** Value for ltShrA. */
    @QuerySqlField
    private Double ltShrA;

    /** Value for stShrA. */
    @QuerySqlField
    private Double stShrA;

    /** Value for asofD. */
    @QuerySqlField
    private Integer asofD;

    /** Value for cdpPrmFirmC. */
    @QuerySqlField
    private String cdpPrmFirmC;

    /** Value for regTyC. */
    @QuerySqlField
    private String regTyC;

    /** Value for accClsfC. */
    @QuerySqlField
    private String accClsfC;

    /** Value for prdtLvC. */
    @QuerySqlField
    private String prdtLvC;

    /** Value for prdtLvSbtyC. */
    @QuerySqlField
    private String prdtLvSbtyC;

    /** Value for lineOfBusC. */
    @QuerySqlField
    private String lineOfBusC;

    /** Value for rconPptgC. */
    @QuerySqlField
    private String rconPptgC;

    /** Value for pmaPptgC. */
    @QuerySqlField
    private String pmaPptgC;

    /** Value for secTyC. */
    @QuerySqlField
    private String secTyC;

    /** Value for prdtC. */
    @QuerySqlField
    private String prdtC;

    /** Value for symbC. */
    @QuerySqlField
    private String symbC;

    /** Value for prcMulrA. */
    @QuerySqlField
    private Double prcMulrA;

    /** Value for coreFundI. */
    @QuerySqlField
    private String coreFundI;

    /** Value for coreFundC. */
    @QuerySqlField
    private String coreFundC;

    /** Value for trdDShtQ. */
    @QuerySqlField
    private Double trdDShtQ;

    /** Value for setlDShtQ. */
    @QuerySqlField
    private Double setlDShtQ;

    /** Value for adjD. */
    @QuerySqlField
    private Integer adjD;

    /** Value for adjAcnC. */
    @QuerySqlField
    private String adjAcnC;

    /** Value for adjRsnC. */
    @QuerySqlField
    private String adjRsnC;

    /** Value for fileRunD. */
    @QuerySqlField
    private Integer fileRunD;

    /** Value for fileAccSrcC. */
    @QuerySqlField
    private String fileAccSrcC;

    /** Value for insrTmst. */
    @QuerySqlField
    private Long insrTmst;

    /** Value for runId. */
    @QuerySqlField
    private String runId;

    /** Value for origTdMkvlA. */
    @QuerySqlField
    private Double origTdMkvlA;

    /** Value for origTdQtyA. */
    @QuerySqlField
    private Double origTdQtyA;

    /** Value for accSrcC. */
    @QuerySqlField
    private String accSrcC;

    /** Value for runD. */
    @QuerySqlField
    private Integer runD;

    public Position() {
        // No-op.
    }

    /**
     * Full constructor.
     */
//    Position(String, long, String, String, String, String, String, String, String, int, String, String, String, String, double, double, double, String, String, double, double, double, double, double,
//    		 double, double, String, int, double, double, double, String, double, String, String, double, double, double, double, double, double, double, double, double, double, int, String, String, String, String,
//    		 String, String, String, String, String, String, String, double, String, String, double, double, int, String, String, int, String, long, String, double, double, String, int)
    public Position(
        String posnId,
        Long posnVerN,
        String accId,
        String accN,
        String csdnC,
        String accTyC,
        String issIdTyC,
        String issId,
        String issSrcC,
        Integer issEffD,
        String srcN,
        String srcNm,
        String plnN,
        String currC,
        Double clsPrcA,
        Double tdMkvlA,
        Double sdMkvlA,
        String tdLngShtC,
        String sdLngShtC,
        Double tdQtyA,
        Double sdQtyA,
        Double sfkShrQ,
        Double trnfShrQ,
        Double lglTrnfShrQ,
        Double nonNegShrQ,
        Double pldgShrQ,
        String mkvlC,
        Integer loclMktPrcD,
        Double loclPrcA,
        Double loclTdMkvlA,
        Double cnvPrcA,
        String mulrDivC,
        Double loclSdMkvlA,
        String ctryC,
        String asetClC,
        Double clsQA,
        Double cbasA,
        Double cbasGnlsA,
        Double mkvlAcriA,
        Double portP,
        Double avgCostA,
        Double ttCostA,
        Double acruIntA,
        Double ltShrA,
        Double stShrA,
        Integer asofD,
        String cdpPrmFirmC,
        String regTyC,
        String accClsfC,
        String prdtLvC,
        String prdtLvSbtyC,
        String lineOfBusC,
        String rconPptgC,
        String pmaPptgC,
        String secTyC,
        String prdtC,
        String symbC,
        Double prcMulrA,
        String coreFundI,
        String coreFundC,
        Double trdDShtQ,
        Double setlDShtQ,
        Integer adjD,
        String adjAcnC,
        String adjRsnC,
        Integer fileRunD,
        String fileAccSrcC,
        Long insrTmst,
        String runId,
        Double origTdMkvlA,
        Double origTdQtyA,
        String accSrcC,
        Integer runD
    ) {
        this.posnId = posnId;
        this.posnVerN = posnVerN;
        this.accId = accId;
        this.accN = accN;
        this.csdnC = csdnC;
        this.accTyC = accTyC;
        this.issIdTyC = issIdTyC;
        this.issId = issId;
        this.issSrcC = issSrcC;
        this.issEffD = issEffD;
        this.srcN = srcN;
        this.srcNm = srcNm;
        this.plnN = plnN;
        this.currC = currC;
        this.clsPrcA = clsPrcA;
        this.tdMkvlA = tdMkvlA;
        this.sdMkvlA = sdMkvlA;
        this.tdLngShtC = tdLngShtC;
        this.sdLngShtC = sdLngShtC;
        this.tdQtyA = tdQtyA;
        this.sdQtyA = sdQtyA;
        this.sfkShrQ = sfkShrQ;
        this.trnfShrQ = trnfShrQ;
        this.lglTrnfShrQ = lglTrnfShrQ;
        this.nonNegShrQ = nonNegShrQ;
        this.pldgShrQ = pldgShrQ;
        this.mkvlC = mkvlC;
        this.loclMktPrcD = loclMktPrcD;
        this.loclPrcA = loclPrcA;
        this.loclTdMkvlA = loclTdMkvlA;
        this.cnvPrcA = cnvPrcA;
        this.mulrDivC = mulrDivC;
        this.loclSdMkvlA = loclSdMkvlA;
        this.ctryC = ctryC;
        this.asetClC = asetClC;
        this.clsQA = clsQA;
        this.cbasA = cbasA;
        this.cbasGnlsA = cbasGnlsA;
        this.mkvlAcriA = mkvlAcriA;
        this.portP = portP;
        this.avgCostA = avgCostA;
        this.ttCostA = ttCostA;
        this.acruIntA = acruIntA;
        this.ltShrA = ltShrA;
        this.stShrA = stShrA;
        this.asofD = asofD;
        this.cdpPrmFirmC = cdpPrmFirmC;
        this.regTyC = regTyC;
        this.accClsfC = accClsfC;
        this.prdtLvC = prdtLvC;
        this.prdtLvSbtyC = prdtLvSbtyC;
        this.lineOfBusC = lineOfBusC;
        this.rconPptgC = rconPptgC;
        this.pmaPptgC = pmaPptgC;
        this.secTyC = secTyC;
        this.prdtC = prdtC;
        this.symbC = symbC;
        this.prcMulrA = prcMulrA;
        this.coreFundI = coreFundI;
        this.coreFundC = coreFundC;
        this.trdDShtQ = trdDShtQ;
        this.setlDShtQ = setlDShtQ;
        this.adjD = adjD;
        this.adjAcnC = adjAcnC;
        this.adjRsnC = adjRsnC;
        this.fileRunD = fileRunD;
        this.fileAccSrcC = fileAccSrcC;
        this.insrTmst = insrTmst;
        this.runId = runId;
        this.origTdMkvlA = origTdMkvlA;
        this.origTdQtyA = origTdQtyA;
        this.accSrcC = accSrcC;
        this.runD = runD;
    }

    /**
     * Gets posnId.
     *
     * @return Value for posnId.
     */


    public String getPosnId() {
        return posnId;
    }

    /**
     * Sets posnId.
     *
     * @param posnId New value for posnId.
     */
    public void setPosnId(String posnId) {
        this.posnId = posnId;
    }

    /**
     * Gets posnVerN.
     *
     * @return Value for posnVerN.
     */
    public Long getPosnVerN() {
        return posnVerN;
    }

    /**
     * Sets posnVerN.
     *
     * @param posnVerN New value for posnVerN.
     */
    public void setPosnVerN(Long posnVerN) {
        this.posnVerN = posnVerN;
    }

    /**
     * Gets accId.
     *
     * @return Value for accId.
     */
    public String getAccId() {
        return accId;
    }

    /**
     * Sets accId.
     *
     * @param accId New value for accId.
     */
    public void setAccId(String accId) {
        this.accId = accId;
    }

    /**
     * Gets accN.
     *
     * @return Value for accN.
     */
    public String getAccN() {
        return accN;
    }

    /**
     * Sets accN.
     *
     * @param accN New value for accN.
     */
    public void setAccN(String accN) {
        this.accN = accN;
    }

    /**
     * Gets csdnC.
     *
     * @return Value for csdnC.
     */
    public String getCsdnC() {
        return csdnC;
    }

    /**
     * Sets csdnC.
     *
     * @param csdnC New value for csdnC.
     */
    public void setCsdnC(String csdnC) {
        this.csdnC = csdnC;
    }

    /**
     * Gets accTyC.
     *
     * @return Value for accTyC.
     */
    public String getAccTyC() {
        return accTyC;
    }

    /**
     * Sets accTyC.
     *
     * @param accTyC New value for accTyC.
     */
    public void setAccTyC(String accTyC) {
        this.accTyC = accTyC;
    }

    /**
     * Gets issIdTyC.
     *
     * @return Value for issIdTyC.
     */
    public String getIssIdTyC() {
        return issIdTyC;
    }

    /**
     * Sets issIdTyC.
     *
     * @param issIdTyC New value for issIdTyC.
     */
    public void setIssIdTyC(String issIdTyC) {
        this.issIdTyC = issIdTyC;
    }

    /**
     * Gets issId.
     *
     * @return Value for issId.
     */
    public String getIssId() {
        return issId;
    }

    /**
     * Sets issId.
     *
     * @param issId New value for issId.
     */
    public void setIssId(String issId) {
        this.issId = issId;
    }

    /**
     * Gets issSrcC.
     *
     * @return Value for issSrcC.
     */
    public String getIssSrcC() {
        return issSrcC;
    }

    /**
     * Sets issSrcC.
     *
     * @param issSrcC New value for issSrcC.
     */
    public void setIssSrcC(String issSrcC) {
        this.issSrcC = issSrcC;
    }

    /**
     * Gets issEffD.
     *
     * @return Value for issEffD.
     */
    public Integer getIssEffD() {
        return issEffD;
    }

    /**
     * Sets issEffD.
     *
     * @param issEffD New value for issEffD.
     */
    public void setIssEffD(Integer issEffD) {
        this.issEffD = issEffD;
    }

    /**
     * Gets srcN.
     *
     * @return Value for srcN.
     */
    public String getSrcN() {
        return srcN;
    }

    /**
     * Sets srcN.
     *
     * @param srcN New value for srcN.
     */
    public void setSrcN(String srcN) {
        this.srcN = srcN;
    }

    /**
     * Gets srcNm.
     *
     * @return Value for srcNm.
     */
    public String getSrcNm() {
        return srcNm;
    }

    /**
     * Sets srcNm.
     *
     * @param srcNm New value for srcNm.
     */
    public void setSrcNm(String srcNm) {
        this.srcNm = srcNm;
    }

    /**
     * Gets plnN.
     *
     * @return Value for plnN.
     */
    public String getPlnN() {
        return plnN;
    }

    /**
     * Sets plnN.
     *
     * @param plnN New value for plnN.
     */
    public void setPlnN(String plnN) {
        this.plnN = plnN;
    }

    /**
     * Gets currC.
     *
     * @return Value for currC.
     */
    public String getCurrC() {
        return currC;
    }

    /**
     * Sets currC.
     *
     * @param currC New value for currC.
     */
    public void setCurrC(String currC) {
        this.currC = currC;
    }

    /**
     * Gets clsPrcA.
     *
     * @return Value for clsPrcA.
     */
    public Double getClsPrcA() {
        return clsPrcA;
    }

    /**
     * Sets clsPrcA.
     *
     * @param clsPrcA New value for clsPrcA.
     */
    public void setClsPrcA(Double clsPrcA) {
        this.clsPrcA = clsPrcA;
    }

    /**
     * Gets tdMkvlA.
     *
     * @return Value for tdMkvlA.
     */
    public Double getTdMkvlA() {
        return tdMkvlA;
    }

    /**
     * Sets tdMkvlA.
     *
     * @param tdMkvlA New value for tdMkvlA.
     */
    public void setTdMkvlA(Double tdMkvlA) {
        this.tdMkvlA = tdMkvlA;
    }

    /**
     * Gets sdMkvlA.
     *
     * @return Value for sdMkvlA.
     */
    public Double getSdMkvlA() {
        return sdMkvlA;
    }

    /**
     * Sets sdMkvlA.
     *
     * @param sdMkvlA New value for sdMkvlA.
     */
    public void setSdMkvlA(Double sdMkvlA) {
        this.sdMkvlA = sdMkvlA;
    }

    /**
     * Gets tdLngShtC.
     *
     * @return Value for tdLngShtC.
     */
    public String getTdLngShtC() {
        return tdLngShtC;
    }

    /**
     * Sets tdLngShtC.
     *
     * @param tdLngShtC New value for tdLngShtC.
     */
    public void setTdLngShtC(String tdLngShtC) {
        this.tdLngShtC = tdLngShtC;
    }

    /**
     * Gets sdLngShtC.
     *
     * @return Value for sdLngShtC.
     */
    public String getSdLngShtC() {
        return sdLngShtC;
    }

    /**
     * Sets sdLngShtC.
     *
     * @param sdLngShtC New value for sdLngShtC.
     */
    public void setSdLngShtC(String sdLngShtC) {
        this.sdLngShtC = sdLngShtC;
    }

    /**
     * Gets tdQtyA.
     *
     * @return Value for tdQtyA.
     */
    public Double getTdQtyA() {
        return tdQtyA;
    }

    /**
     * Sets tdQtyA.
     *
     * @param tdQtyA New value for tdQtyA.
     */
    public void setTdQtyA(Double tdQtyA) {
        this.tdQtyA = tdQtyA;
    }

    /**
     * Gets sdQtyA.
     *
     * @return Value for sdQtyA.
     */
    public Double getSdQtyA() {
        return sdQtyA;
    }

    /**
     * Sets sdQtyA.
     *
     * @param sdQtyA New value for sdQtyA.
     */
    public void setSdQtyA(Double sdQtyA) {
        this.sdQtyA = sdQtyA;
    }

    /**
     * Gets sfkShrQ.
     *
     * @return Value for sfkShrQ.
     */
    public Double getSfkShrQ() {
        return sfkShrQ;
    }

    /**
     * Sets sfkShrQ.
     *
     * @param sfkShrQ New value for sfkShrQ.
     */
    public void setSfkShrQ(Double sfkShrQ) {
        this.sfkShrQ = sfkShrQ;
    }

    /**
     * Gets trnfShrQ.
     *
     * @return Value for trnfShrQ.
     */
    public Double getTrnfShrQ() {
        return trnfShrQ;
    }

    /**
     * Sets trnfShrQ.
     *
     * @param trnfShrQ New value for trnfShrQ.
     */
    public void setTrnfShrQ(Double trnfShrQ) {
        this.trnfShrQ = trnfShrQ;
    }

    /**
     * Gets lglTrnfShrQ.
     *
     * @return Value for lglTrnfShrQ.
     */
    public Double getLglTrnfShrQ() {
        return lglTrnfShrQ;
    }

    /**
     * Sets lglTrnfShrQ.
     *
     * @param lglTrnfShrQ New value for lglTrnfShrQ.
     */
    public void setLglTrnfShrQ(Double lglTrnfShrQ) {
        this.lglTrnfShrQ = lglTrnfShrQ;
    }

    /**
     * Gets nonNegShrQ.
     *
     * @return Value for nonNegShrQ.
     */
    public Double getNonNegShrQ() {
        return nonNegShrQ;
    }

    /**
     * Sets nonNegShrQ.
     *
     * @param nonNegShrQ New value for nonNegShrQ.
     */
    public void setNonNegShrQ(Double nonNegShrQ) {
        this.nonNegShrQ = nonNegShrQ;
    }

    /**
     * Gets pldgShrQ.
     *
     * @return Value for pldgShrQ.
     */
    public Double getPldgShrQ() {
        return pldgShrQ;
    }

    /**
     * Sets pldgShrQ.
     *
     * @param pldgShrQ New value for pldgShrQ.
     */
    public void setPldgShrQ(Double pldgShrQ) {
        this.pldgShrQ = pldgShrQ;
    }

    /**
     * Gets mkvlC.
     *
     * @return Value for mkvlC.
     */
    public String getMkvlC() {
        return mkvlC;
    }

    /**
     * Sets mkvlC.
     *
     * @param mkvlC New value for mkvlC.
     */
    public void setMkvlC(String mkvlC) {
        this.mkvlC = mkvlC;
    }

    /**
     * Gets loclMktPrcD.
     *
     * @return Value for loclMktPrcD.
     */
    public Integer getLoclMktPrcD() {
        return loclMktPrcD;
    }

    /**
     * Sets loclMktPrcD.
     *
     * @param loclMktPrcD New value for loclMktPrcD.
     */
    public void setLoclMktPrcD(Integer loclMktPrcD) {
        this.loclMktPrcD = loclMktPrcD;
    }

    /**
     * Gets loclPrcA.
     *
     * @return Value for loclPrcA.
     */
    public Double getLoclPrcA() {
        return loclPrcA;
    }

    /**
     * Sets loclPrcA.
     *
     * @param loclPrcA New value for loclPrcA.
     */
    public void setLoclPrcA(Double loclPrcA) {
        this.loclPrcA = loclPrcA;
    }

    /**
     * Gets loclTdMkvlA.
     *
     * @return Value for loclTdMkvlA.
     */
    public Double getLoclTdMkvlA() {
        return loclTdMkvlA;
    }

    /**
     * Sets loclTdMkvlA.
     *
     * @param loclTdMkvlA New value for loclTdMkvlA.
     */
    public void setLoclTdMkvlA(Double loclTdMkvlA) {
        this.loclTdMkvlA = loclTdMkvlA;
    }

    /**
     * Gets cnvPrcA.
     *
     * @return Value for cnvPrcA.
     */
    public Double getCnvPrcA() {
        return cnvPrcA;
    }

    /**
     * Sets cnvPrcA.
     *
     * @param cnvPrcA New value for cnvPrcA.
     */
    public void setCnvPrcA(Double cnvPrcA) {
        this.cnvPrcA = cnvPrcA;
    }

    /**
     * Gets mulrDivC.
     *
     * @return Value for mulrDivC.
     */
    public String getMulrDivC() {
        return mulrDivC;
    }

    /**
     * Sets mulrDivC.
     *
     * @param mulrDivC New value for mulrDivC.
     */
    public void setMulrDivC(String mulrDivC) {
        this.mulrDivC = mulrDivC;
    }

    /**
     * Gets loclSdMkvlA.
     *
     * @return Value for loclSdMkvlA.
     */
    public Double getLoclSdMkvlA() {
        return loclSdMkvlA;
    }

    /**
     * Sets loclSdMkvlA.
     *
     * @param loclSdMkvlA New value for loclSdMkvlA.
     */
    public void setLoclSdMkvlA(Double loclSdMkvlA) {
        this.loclSdMkvlA = loclSdMkvlA;
    }

    /**
     * Gets ctryC.
     *
     * @return Value for ctryC.
     */
    public String getCtryC() {
        return ctryC;
    }

    /**
     * Sets ctryC.
     *
     * @param ctryC New value for ctryC.
     */
    public void setCtryC(String ctryC) {
        this.ctryC = ctryC;
    }

    /**
     * Gets asetClC.
     *
     * @return Value for asetClC.
     */
    public String getAsetClC() {
        return asetClC;
    }

    /**
     * Sets asetClC.
     *
     * @param asetClC New value for asetClC.
     */
    public void setAsetClC(String asetClC) {
        this.asetClC = asetClC;
    }

    /**
     * Gets clsQA.
     *
     * @return Value for clsQA.
     */
    public Double getClsQA() {
        return clsQA;
    }

    /**
     * Sets clsQA.
     *
     * @param clsQA New value for clsQA.
     */
    public void setClsQA(Double clsQA) {
        this.clsQA = clsQA;
    }

    /**
     * Gets cbasA.
     *
     * @return Value for cbasA.
     */
    public Double getCbasA() {
        return cbasA;
    }

    /**
     * Sets cbasA.
     *
     * @param cbasA New value for cbasA.
     */
    public void setCbasA(Double cbasA) {
        this.cbasA = cbasA;
    }

    /**
     * Gets cbasGnlsA.
     *
     * @return Value for cbasGnlsA.
     */
    public Double getCbasGnlsA() {
        return cbasGnlsA;
    }

    /**
     * Sets cbasGnlsA.
     *
     * @param cbasGnlsA New value for cbasGnlsA.
     */
    public void setCbasGnlsA(Double cbasGnlsA) {
        this.cbasGnlsA = cbasGnlsA;
    }

    /**
     * Gets mkvlAcriA.
     *
     * @return Value for mkvlAcriA.
     */
    public Double getMkvlAcriA() {
        return mkvlAcriA;
    }

    /**
     * Sets mkvlAcriA.
     *
     * @param mkvlAcriA New value for mkvlAcriA.
     */
    public void setMkvlAcriA(Double mkvlAcriA) {
        this.mkvlAcriA = mkvlAcriA;
    }

    /**
     * Gets portP.
     *
     * @return Value for portP.
     */
    public Double getPortP() {
        return portP;
    }

    /**
     * Sets portP.
     *
     * @param portP New value for portP.
     */
    public void setPortP(Double portP) {
        this.portP = portP;
    }

    /**
     * Gets avgCostA.
     *
     * @return Value for avgCostA.
     */
    public Double getAvgCostA() {
        return avgCostA;
    }

    /**
     * Sets avgCostA.
     *
     * @param avgCostA New value for avgCostA.
     */
    public void setAvgCostA(Double avgCostA) {
        this.avgCostA = avgCostA;
    }

    /**
     * Gets ttCostA.
     *
     * @return Value for ttCostA.
     */
    public Double getTtCostA() {
        return ttCostA;
    }

    /**
     * Sets ttCostA.
     *
     * @param ttCostA New value for ttCostA.
     */
    public void setTtCostA(Double ttCostA) {
        this.ttCostA = ttCostA;
    }

    /**
     * Gets acruIntA.
     *
     * @return Value for acruIntA.
     */
    public Double getAcruIntA() {
        return acruIntA;
    }

    /**
     * Sets acruIntA.
     *
     * @param acruIntA New value for acruIntA.
     */
    public void setAcruIntA(Double acruIntA) {
        this.acruIntA = acruIntA;
    }

    /**
     * Gets ltShrA.
     *
     * @return Value for ltShrA.
     */
    public Double getLtShrA() {
        return ltShrA;
    }

    /**
     * Sets ltShrA.
     *
     * @param ltShrA New value for ltShrA.
     */
    public void setLtShrA(Double ltShrA) {
        this.ltShrA = ltShrA;
    }

    /**
     * Gets stShrA.
     *
     * @return Value for stShrA.
     */
    public Double getStShrA() {
        return stShrA;
    }

    /**
     * Sets stShrA.
     *
     * @param stShrA New value for stShrA.
     */
    public void setStShrA(Double stShrA) {
        this.stShrA = stShrA;
    }

    /**
     * Gets asofD.
     *
     * @return Value for asofD.
     */
    public Integer getAsofD() {
        return asofD;
    }

    /**
     * Sets asofD.
     *
     * @param asofD New value for asofD.
     */
    public void setAsofD(Integer asofD) {
        this.asofD = asofD;
    }

    /**
     * Gets cdpPrmFirmC.
     *
     * @return Value for cdpPrmFirmC.
     */
    public String getCdpPrmFirmC() {
        return cdpPrmFirmC;
    }

    /**
     * Sets cdpPrmFirmC.
     *
     * @param cdpPrmFirmC New value for cdpPrmFirmC.
     */
    public void setCdpPrmFirmC(String cdpPrmFirmC) {
        this.cdpPrmFirmC = cdpPrmFirmC;
    }

    /**
     * Gets regTyC.
     *
     * @return Value for regTyC.
     */
    public String getRegTyC() {
        return regTyC;
    }

    /**
     * Sets regTyC.
     *
     * @param regTyC New value for regTyC.
     */
    public void setRegTyC(String regTyC) {
        this.regTyC = regTyC;
    }

    /**
     * Gets accClsfC.
     *
     * @return Value for accClsfC.
     */
    public String getAccClsfC() {
        return accClsfC;
    }

    /**
     * Sets accClsfC.
     *
     * @param accClsfC New value for accClsfC.
     */
    public void setAccClsfC(String accClsfC) {
        this.accClsfC = accClsfC;
    }

    /**
     * Gets prdtLvC.
     *
     * @return Value for prdtLvC.
     */
    public String getPrdtLvC() {
        return prdtLvC;
    }

    /**
     * Sets prdtLvC.
     *
     * @param prdtLvC New value for prdtLvC.
     */
    public void setPrdtLvC(String prdtLvC) {
        this.prdtLvC = prdtLvC;
    }

    /**
     * Gets prdtLvSbtyC.
     *
     * @return Value for prdtLvSbtyC.
     */
    public String getPrdtLvSbtyC() {
        return prdtLvSbtyC;
    }

    /**
     * Sets prdtLvSbtyC.
     *
     * @param prdtLvSbtyC New value for prdtLvSbtyC.
     */
    public void setPrdtLvSbtyC(String prdtLvSbtyC) {
        this.prdtLvSbtyC = prdtLvSbtyC;
    }

    /**
     * Gets lineOfBusC.
     *
     * @return Value for lineOfBusC.
     */
    public String getLineOfBusC() {
        return lineOfBusC;
    }

    /**
     * Sets lineOfBusC.
     *
     * @param lineOfBusC New value for lineOfBusC.
     */
    public void setLineOfBusC(String lineOfBusC) {
        this.lineOfBusC = lineOfBusC;
    }

    /**
     * Gets rconPptgC.
     *
     * @return Value for rconPptgC.
     */
    public String getRconPptgC() {
        return rconPptgC;
    }

    /**
     * Sets rconPptgC.
     *
     * @param rconPptgC New value for rconPptgC.
     */
    public void setRconPptgC(String rconPptgC) {
        this.rconPptgC = rconPptgC;
    }

    /**
     * Gets pmaPptgC.
     *
     * @return Value for pmaPptgC.
     */
    public String getPmaPptgC() {
        return pmaPptgC;
    }

    /**
     * Sets pmaPptgC.
     *
     * @param pmaPptgC New value for pmaPptgC.
     */
    public void setPmaPptgC(String pmaPptgC) {
        this.pmaPptgC = pmaPptgC;
    }

    /**
     * Gets secTyC.
     *
     * @return Value for secTyC.
     */
    public String getSecTyC() {
        return secTyC;
    }

    /**
     * Sets secTyC.
     *
     * @param secTyC New value for secTyC.
     */
    public void setSecTyC(String secTyC) {
        this.secTyC = secTyC;
    }

    /**
     * Gets prdtC.
     *
     * @return Value for prdtC.
     */
    public String getPrdtC() {
        return prdtC;
    }

    /**
     * Sets prdtC.
     *
     * @param prdtC New value for prdtC.
     */
    public void setPrdtC(String prdtC) {
        this.prdtC = prdtC;
    }

    /**
     * Gets symbC.
     *
     * @return Value for symbC.
     */
    public String getSymbC() {
        return symbC;
    }

    /**
     * Sets symbC.
     *
     * @param symbC New value for symbC.
     */
    public void setSymbC(String symbC) {
        this.symbC = symbC;
    }

    /**
     * Gets prcMulrA.
     *
     * @return Value for prcMulrA.
     */
    public Double getPrcMulrA() {
        return prcMulrA;
    }

    /**
     * Sets prcMulrA.
     *
     * @param prcMulrA New value for prcMulrA.
     */
    public void setPrcMulrA(Double prcMulrA) {
        this.prcMulrA = prcMulrA;
    }

    /**
     * Gets coreFundI.
     *
     * @return Value for coreFundI.
     */
    public String getCoreFundI() {
        return coreFundI;
    }

    /**
     * Sets coreFundI.
     *
     * @param coreFundI New value for coreFundI.
     */
    public void setCoreFundI(String coreFundI) {
        this.coreFundI = coreFundI;
    }

    /**
     * Gets coreFundC.
     *
     * @return Value for coreFundC.
     */
    public String getCoreFundC() {
        return coreFundC;
    }

    /**
     * Sets coreFundC.
     *
     * @param coreFundC New value for coreFundC.
     */
    public void setCoreFundC(String coreFundC) {
        this.coreFundC = coreFundC;
    }

    /**
     * Gets trdDShtQ.
     *
     * @return Value for trdDShtQ.
     */
    public Double getTrdDShtQ() {
        return trdDShtQ;
    }

    /**
     * Sets trdDShtQ.
     *
     * @param trdDShtQ New value for trdDShtQ.
     */
    public void setTrdDShtQ(Double trdDShtQ) {
        this.trdDShtQ = trdDShtQ;
    }

    /**
     * Gets setlDShtQ.
     *
     * @return Value for setlDShtQ.
     */
    public Double getSetlDShtQ() {
        return setlDShtQ;
    }

    /**
     * Sets setlDShtQ.
     *
     * @param setlDShtQ New value for setlDShtQ.
     */
    public void setSetlDShtQ(Double setlDShtQ) {
        this.setlDShtQ = setlDShtQ;
    }

    /**
     * Gets adjD.
     *
     * @return Value for adjD.
     */
    public Integer getAdjD() {
        return adjD;
    }

    /**
     * Sets adjD.
     *
     * @param adjD New value for adjD.
     */
    public void setAdjD(Integer adjD) {
        this.adjD = adjD;
    }

    /**
     * Gets adjAcnC.
     *
     * @return Value for adjAcnC.
     */
    public String getAdjAcnC() {
        return adjAcnC;
    }

    /**
     * Sets adjAcnC.
     *
     * @param adjAcnC New value for adjAcnC.
     */
    public void setAdjAcnC(String adjAcnC) {
        this.adjAcnC = adjAcnC;
    }

    /**
     * Gets adjRsnC.
     *
     * @return Value for adjRsnC.
     */
    public String getAdjRsnC() {
        return adjRsnC;
    }

    /**
     * Sets adjRsnC.
     *
     * @param adjRsnC New value for adjRsnC.
     */
    public void setAdjRsnC(String adjRsnC) {
        this.adjRsnC = adjRsnC;
    }

    /**
     * Gets fileRunD.
     *
     * @return Value for fileRunD.
     */
    public Integer getFileRunD() {
        return fileRunD;
    }

    /**
     * Sets fileRunD.
     *
     * @param fileRunD New value for fileRunD.
     */
    public void setFileRunD(Integer fileRunD) {
        this.fileRunD = fileRunD;
    }

    /**
     * Gets fileAccSrcC.
     *
     * @return Value for fileAccSrcC.
     */
    public String getFileAccSrcC() {
        return fileAccSrcC;
    }

    /**
     * Sets fileAccSrcC.
     *
     * @param fileAccSrcC New value for fileAccSrcC.
     */
    public void setFileAccSrcC(String fileAccSrcC) {
        this.fileAccSrcC = fileAccSrcC;
    }

    /**
     * Gets insrTmst.
     *
     * @return Value for insrTmst.
     */
    public Long getInsrTmst() {
        return insrTmst;
    }

    /**
     * Sets insrTmst.
     *
     * @param insrTmst New value for insrTmst.
     */
    public void setInsrTmst(Long insrTmst) {
        this.insrTmst = insrTmst;
    }

    /**
     * Gets runId.
     *
     * @return Value for runId.
     */
    public String getRunId() {
        return runId;
    }

    /**
     * Sets runId.
     *
     * @param runId New value for runId.
     */
    public void setRunId(String runId) {
        this.runId = runId;
    }

    /**
     * Gets origTdMkvlA.
     *
     * @return Value for origTdMkvlA.
     */
    public Double getOrigTdMkvlA() {
        return origTdMkvlA;
    }

    /**
     * Sets origTdMkvlA.
     *
     * @param origTdMkvlA New value for origTdMkvlA.
     */
    public void setOrigTdMkvlA(Double origTdMkvlA) {
        this.origTdMkvlA = origTdMkvlA;
    }

    /**
     * Gets origTdQtyA.
     *
     * @return Value for origTdQtyA.
     */
    public Double getOrigTdQtyA() {
        return origTdQtyA;
    }

    /**
     * Sets origTdQtyA.
     *
     * @param origTdQtyA New value for origTdQtyA.
     */
    public void setOrigTdQtyA(Double origTdQtyA) {
        this.origTdQtyA = origTdQtyA;
    }

    /**
     * Gets accSrcC.
     *
     * @return Value for accSrcC.
     */
    public String getAccSrcC() {
        return accSrcC;
    }

    /**
     * Sets accSrcC.
     *
     * @param accSrcC New value for accSrcC.
     */
    public void setAccSrcC(String accSrcC) {
        this.accSrcC = accSrcC;
    }

    /**
     * Gets runD.
     *
     * @return Value for runD.
     */
    public Integer getRunD() {
        return runD;
    }

    /**
     * Sets runD.
     *
     * @param runD New value for runD.
     */
    public void setRunD(Integer runD) {
        this.runD = runD;
    }

    /** {@inheritDoc} */
    @Override public boolean equals(Object o) {
        if (this == o)
            return true;

        if (!(o instanceof Position))
            return false;

        Position that = (Position)o;

        if (posnId != null ? !posnId.equals(that.posnId) : that.posnId != null)
            return false;

        if (posnVerN != null ? !posnVerN.equals(that.posnVerN) : that.posnVerN != null)
            return false;

        if (accId != null ? !accId.equals(that.accId) : that.accId != null)
            return false;

        if (accN != null ? !accN.equals(that.accN) : that.accN != null)
            return false;

        if (csdnC != null ? !csdnC.equals(that.csdnC) : that.csdnC != null)
            return false;

        if (accTyC != null ? !accTyC.equals(that.accTyC) : that.accTyC != null)
            return false;

        if (issIdTyC != null ? !issIdTyC.equals(that.issIdTyC) : that.issIdTyC != null)
            return false;

        if (issId != null ? !issId.equals(that.issId) : that.issId != null)
            return false;

        if (issSrcC != null ? !issSrcC.equals(that.issSrcC) : that.issSrcC != null)
            return false;

        if (issEffD != null ? !issEffD.equals(that.issEffD) : that.issEffD != null)
            return false;

        if (srcN != null ? !srcN.equals(that.srcN) : that.srcN != null)
            return false;

        if (srcNm != null ? !srcNm.equals(that.srcNm) : that.srcNm != null)
            return false;

        if (plnN != null ? !plnN.equals(that.plnN) : that.plnN != null)
            return false;

        if (currC != null ? !currC.equals(that.currC) : that.currC != null)
            return false;

        if (clsPrcA != null ? !clsPrcA.equals(that.clsPrcA) : that.clsPrcA != null)
            return false;

        if (tdMkvlA != null ? !tdMkvlA.equals(that.tdMkvlA) : that.tdMkvlA != null)
            return false;

        if (sdMkvlA != null ? !sdMkvlA.equals(that.sdMkvlA) : that.sdMkvlA != null)
            return false;

        if (tdLngShtC != null ? !tdLngShtC.equals(that.tdLngShtC) : that.tdLngShtC != null)
            return false;

        if (sdLngShtC != null ? !sdLngShtC.equals(that.sdLngShtC) : that.sdLngShtC != null)
            return false;

        if (tdQtyA != null ? !tdQtyA.equals(that.tdQtyA) : that.tdQtyA != null)
            return false;

        if (sdQtyA != null ? !sdQtyA.equals(that.sdQtyA) : that.sdQtyA != null)
            return false;

        if (sfkShrQ != null ? !sfkShrQ.equals(that.sfkShrQ) : that.sfkShrQ != null)
            return false;

        if (trnfShrQ != null ? !trnfShrQ.equals(that.trnfShrQ) : that.trnfShrQ != null)
            return false;

        if (lglTrnfShrQ != null ? !lglTrnfShrQ.equals(that.lglTrnfShrQ) : that.lglTrnfShrQ != null)
            return false;

        if (nonNegShrQ != null ? !nonNegShrQ.equals(that.nonNegShrQ) : that.nonNegShrQ != null)
            return false;

        if (pldgShrQ != null ? !pldgShrQ.equals(that.pldgShrQ) : that.pldgShrQ != null)
            return false;

        if (mkvlC != null ? !mkvlC.equals(that.mkvlC) : that.mkvlC != null)
            return false;

        if (loclMktPrcD != null ? !loclMktPrcD.equals(that.loclMktPrcD) : that.loclMktPrcD != null)
            return false;

        if (loclPrcA != null ? !loclPrcA.equals(that.loclPrcA) : that.loclPrcA != null)
            return false;

        if (loclTdMkvlA != null ? !loclTdMkvlA.equals(that.loclTdMkvlA) : that.loclTdMkvlA != null)
            return false;

        if (cnvPrcA != null ? !cnvPrcA.equals(that.cnvPrcA) : that.cnvPrcA != null)
            return false;

        if (mulrDivC != null ? !mulrDivC.equals(that.mulrDivC) : that.mulrDivC != null)
            return false;

        if (loclSdMkvlA != null ? !loclSdMkvlA.equals(that.loclSdMkvlA) : that.loclSdMkvlA != null)
            return false;

        if (ctryC != null ? !ctryC.equals(that.ctryC) : that.ctryC != null)
            return false;

        if (asetClC != null ? !asetClC.equals(that.asetClC) : that.asetClC != null)
            return false;

        if (clsQA != null ? !clsQA.equals(that.clsQA) : that.clsQA != null)
            return false;

        if (cbasA != null ? !cbasA.equals(that.cbasA) : that.cbasA != null)
            return false;

        if (cbasGnlsA != null ? !cbasGnlsA.equals(that.cbasGnlsA) : that.cbasGnlsA != null)
            return false;

        if (mkvlAcriA != null ? !mkvlAcriA.equals(that.mkvlAcriA) : that.mkvlAcriA != null)
            return false;

        if (portP != null ? !portP.equals(that.portP) : that.portP != null)
            return false;

        if (avgCostA != null ? !avgCostA.equals(that.avgCostA) : that.avgCostA != null)
            return false;

        if (ttCostA != null ? !ttCostA.equals(that.ttCostA) : that.ttCostA != null)
            return false;

        if (acruIntA != null ? !acruIntA.equals(that.acruIntA) : that.acruIntA != null)
            return false;

        if (ltShrA != null ? !ltShrA.equals(that.ltShrA) : that.ltShrA != null)
            return false;

        if (stShrA != null ? !stShrA.equals(that.stShrA) : that.stShrA != null)
            return false;

        if (asofD != null ? !asofD.equals(that.asofD) : that.asofD != null)
            return false;

        if (cdpPrmFirmC != null ? !cdpPrmFirmC.equals(that.cdpPrmFirmC) : that.cdpPrmFirmC != null)
            return false;

        if (regTyC != null ? !regTyC.equals(that.regTyC) : that.regTyC != null)
            return false;

        if (accClsfC != null ? !accClsfC.equals(that.accClsfC) : that.accClsfC != null)
            return false;

        if (prdtLvC != null ? !prdtLvC.equals(that.prdtLvC) : that.prdtLvC != null)
            return false;

        if (prdtLvSbtyC != null ? !prdtLvSbtyC.equals(that.prdtLvSbtyC) : that.prdtLvSbtyC != null)
            return false;

        if (lineOfBusC != null ? !lineOfBusC.equals(that.lineOfBusC) : that.lineOfBusC != null)
            return false;

        if (rconPptgC != null ? !rconPptgC.equals(that.rconPptgC) : that.rconPptgC != null)
            return false;

        if (pmaPptgC != null ? !pmaPptgC.equals(that.pmaPptgC) : that.pmaPptgC != null)
            return false;

        if (secTyC != null ? !secTyC.equals(that.secTyC) : that.secTyC != null)
            return false;

        if (prdtC != null ? !prdtC.equals(that.prdtC) : that.prdtC != null)
            return false;

        if (symbC != null ? !symbC.equals(that.symbC) : that.symbC != null)
            return false;

        if (prcMulrA != null ? !prcMulrA.equals(that.prcMulrA) : that.prcMulrA != null)
            return false;

        if (coreFundI != null ? !coreFundI.equals(that.coreFundI) : that.coreFundI != null)
            return false;

        if (coreFundC != null ? !coreFundC.equals(that.coreFundC) : that.coreFundC != null)
            return false;

        if (trdDShtQ != null ? !trdDShtQ.equals(that.trdDShtQ) : that.trdDShtQ != null)
            return false;

        if (setlDShtQ != null ? !setlDShtQ.equals(that.setlDShtQ) : that.setlDShtQ != null)
            return false;

        if (adjD != null ? !adjD.equals(that.adjD) : that.adjD != null)
            return false;

        if (adjAcnC != null ? !adjAcnC.equals(that.adjAcnC) : that.adjAcnC != null)
            return false;

        if (adjRsnC != null ? !adjRsnC.equals(that.adjRsnC) : that.adjRsnC != null)
            return false;

        if (fileRunD != null ? !fileRunD.equals(that.fileRunD) : that.fileRunD != null)
            return false;

        if (fileAccSrcC != null ? !fileAccSrcC.equals(that.fileAccSrcC) : that.fileAccSrcC != null)
            return false;

        if (insrTmst != null ? !insrTmst.equals(that.insrTmst) : that.insrTmst != null)
            return false;

        if (runId != null ? !runId.equals(that.runId) : that.runId != null)
            return false;

        if (origTdMkvlA != null ? !origTdMkvlA.equals(that.origTdMkvlA) : that.origTdMkvlA != null)
            return false;

        if (origTdQtyA != null ? !origTdQtyA.equals(that.origTdQtyA) : that.origTdQtyA != null)
            return false;

        if (accSrcC != null ? !accSrcC.equals(that.accSrcC) : that.accSrcC != null)
            return false;

        if (runD != null ? !runD.equals(that.runD) : that.runD != null)
            return false;

        return true;
    }

    /** {@inheritDoc} */
    @Override public int hashCode() {
        int res = posnId != null ? posnId.hashCode() : 0;

        res = 31 * res + (posnVerN != null ? posnVerN.hashCode() : 0);

        res = 31 * res + (accId != null ? accId.hashCode() : 0);

        res = 31 * res + (accN != null ? accN.hashCode() : 0);

        res = 31 * res + (csdnC != null ? csdnC.hashCode() : 0);

        res = 31 * res + (accTyC != null ? accTyC.hashCode() : 0);

        res = 31 * res + (issIdTyC != null ? issIdTyC.hashCode() : 0);

        res = 31 * res + (issId != null ? issId.hashCode() : 0);

        res = 31 * res + (issSrcC != null ? issSrcC.hashCode() : 0);

        res = 31 * res + (issEffD != null ? issEffD.hashCode() : 0);

        res = 31 * res + (srcN != null ? srcN.hashCode() : 0);

        res = 31 * res + (srcNm != null ? srcNm.hashCode() : 0);

        res = 31 * res + (plnN != null ? plnN.hashCode() : 0);

        res = 31 * res + (currC != null ? currC.hashCode() : 0);

        res = 31 * res + (clsPrcA != null ? clsPrcA.hashCode() : 0);

        res = 31 * res + (tdMkvlA != null ? tdMkvlA.hashCode() : 0);

        res = 31 * res + (sdMkvlA != null ? sdMkvlA.hashCode() : 0);

        res = 31 * res + (tdLngShtC != null ? tdLngShtC.hashCode() : 0);

        res = 31 * res + (sdLngShtC != null ? sdLngShtC.hashCode() : 0);

        res = 31 * res + (tdQtyA != null ? tdQtyA.hashCode() : 0);

        res = 31 * res + (sdQtyA != null ? sdQtyA.hashCode() : 0);

        res = 31 * res + (sfkShrQ != null ? sfkShrQ.hashCode() : 0);

        res = 31 * res + (trnfShrQ != null ? trnfShrQ.hashCode() : 0);

        res = 31 * res + (lglTrnfShrQ != null ? lglTrnfShrQ.hashCode() : 0);

        res = 31 * res + (nonNegShrQ != null ? nonNegShrQ.hashCode() : 0);

        res = 31 * res + (pldgShrQ != null ? pldgShrQ.hashCode() : 0);

        res = 31 * res + (mkvlC != null ? mkvlC.hashCode() : 0);

        res = 31 * res + (loclMktPrcD != null ? loclMktPrcD.hashCode() : 0);

        res = 31 * res + (loclPrcA != null ? loclPrcA.hashCode() : 0);

        res = 31 * res + (loclTdMkvlA != null ? loclTdMkvlA.hashCode() : 0);

        res = 31 * res + (cnvPrcA != null ? cnvPrcA.hashCode() : 0);

        res = 31 * res + (mulrDivC != null ? mulrDivC.hashCode() : 0);

        res = 31 * res + (loclSdMkvlA != null ? loclSdMkvlA.hashCode() : 0);

        res = 31 * res + (ctryC != null ? ctryC.hashCode() : 0);

        res = 31 * res + (asetClC != null ? asetClC.hashCode() : 0);

        res = 31 * res + (clsQA != null ? clsQA.hashCode() : 0);

        res = 31 * res + (cbasA != null ? cbasA.hashCode() : 0);

        res = 31 * res + (cbasGnlsA != null ? cbasGnlsA.hashCode() : 0);

        res = 31 * res + (mkvlAcriA != null ? mkvlAcriA.hashCode() : 0);

        res = 31 * res + (portP != null ? portP.hashCode() : 0);

        res = 31 * res + (avgCostA != null ? avgCostA.hashCode() : 0);

        res = 31 * res + (ttCostA != null ? ttCostA.hashCode() : 0);

        res = 31 * res + (acruIntA != null ? acruIntA.hashCode() : 0);

        res = 31 * res + (ltShrA != null ? ltShrA.hashCode() : 0);

        res = 31 * res + (stShrA != null ? stShrA.hashCode() : 0);

        res = 31 * res + (asofD != null ? asofD.hashCode() : 0);

        res = 31 * res + (cdpPrmFirmC != null ? cdpPrmFirmC.hashCode() : 0);

        res = 31 * res + (regTyC != null ? regTyC.hashCode() : 0);

        res = 31 * res + (accClsfC != null ? accClsfC.hashCode() : 0);

        res = 31 * res + (prdtLvC != null ? prdtLvC.hashCode() : 0);

        res = 31 * res + (prdtLvSbtyC != null ? prdtLvSbtyC.hashCode() : 0);

        res = 31 * res + (lineOfBusC != null ? lineOfBusC.hashCode() : 0);

        res = 31 * res + (rconPptgC != null ? rconPptgC.hashCode() : 0);

        res = 31 * res + (pmaPptgC != null ? pmaPptgC.hashCode() : 0);

        res = 31 * res + (secTyC != null ? secTyC.hashCode() : 0);

        res = 31 * res + (prdtC != null ? prdtC.hashCode() : 0);

        res = 31 * res + (symbC != null ? symbC.hashCode() : 0);

        res = 31 * res + (prcMulrA != null ? prcMulrA.hashCode() : 0);

        res = 31 * res + (coreFundI != null ? coreFundI.hashCode() : 0);

        res = 31 * res + (coreFundC != null ? coreFundC.hashCode() : 0);

        res = 31 * res + (trdDShtQ != null ? trdDShtQ.hashCode() : 0);

        res = 31 * res + (setlDShtQ != null ? setlDShtQ.hashCode() : 0);

        res = 31 * res + (adjD != null ? adjD.hashCode() : 0);

        res = 31 * res + (adjAcnC != null ? adjAcnC.hashCode() : 0);

        res = 31 * res + (adjRsnC != null ? adjRsnC.hashCode() : 0);

        res = 31 * res + (fileRunD != null ? fileRunD.hashCode() : 0);

        res = 31 * res + (fileAccSrcC != null ? fileAccSrcC.hashCode() : 0);

        res = 31 * res + (insrTmst != null ? insrTmst.hashCode() : 0);

        res = 31 * res + (runId != null ? runId.hashCode() : 0);

        res = 31 * res + (origTdMkvlA != null ? origTdMkvlA.hashCode() : 0);

        res = 31 * res + (origTdQtyA != null ? origTdQtyA.hashCode() : 0);

        res = 31 * res + (accSrcC != null ? accSrcC.hashCode() : 0);

        res = 31 * res + (runD != null ? runD.hashCode() : 0);

        return res;
    }

    /** {@inheritDoc} */
    @Override public String toString() {
        return "Position [posnId=" + posnId +
            ", posnVerN=" + posnVerN +
            ", accId=" + accId +
            ", accN=" + accN +
            ", csdnC=" + csdnC +
            ", accTyC=" + accTyC +
            ", issIdTyC=" + issIdTyC +
            ", issId=" + issId +
            ", issSrcC=" + issSrcC +
            ", issEffD=" + issEffD +
            ", srcN=" + srcN +
            ", srcNm=" + srcNm +
            ", plnN=" + plnN +
            ", currC=" + currC +
            ", clsPrcA=" + clsPrcA +
            ", tdMkvlA=" + tdMkvlA +
            ", sdMkvlA=" + sdMkvlA +
            ", tdLngShtC=" + tdLngShtC +
            ", sdLngShtC=" + sdLngShtC +
            ", tdQtyA=" + tdQtyA +
            ", sdQtyA=" + sdQtyA +
            ", sfkShrQ=" + sfkShrQ +
            ", trnfShrQ=" + trnfShrQ +
            ", lglTrnfShrQ=" + lglTrnfShrQ +
            ", nonNegShrQ=" + nonNegShrQ +
            ", pldgShrQ=" + pldgShrQ +
            ", mkvlC=" + mkvlC +
            ", loclMktPrcD=" + loclMktPrcD +
            ", loclPrcA=" + loclPrcA +
            ", loclTdMkvlA=" + loclTdMkvlA +
            ", cnvPrcA=" + cnvPrcA +
            ", mulrDivC=" + mulrDivC +
            ", loclSdMkvlA=" + loclSdMkvlA +
            ", ctryC=" + ctryC +
            ", asetClC=" + asetClC +
            ", clsQA=" + clsQA +
            ", cbasA=" + cbasA +
            ", cbasGnlsA=" + cbasGnlsA +
            ", mkvlAcriA=" + mkvlAcriA +
            ", portP=" + portP +
            ", avgCostA=" + avgCostA +
            ", ttCostA=" + ttCostA +
            ", acruIntA=" + acruIntA +
            ", ltShrA=" + ltShrA +
            ", stShrA=" + stShrA +
            ", asofD=" + asofD +
            ", cdpPrmFirmC=" + cdpPrmFirmC +
            ", regTyC=" + regTyC +
            ", accClsfC=" + accClsfC +
            ", prdtLvC=" + prdtLvC +
            ", prdtLvSbtyC=" + prdtLvSbtyC +
            ", lineOfBusC=" + lineOfBusC +
            ", rconPptgC=" + rconPptgC +
            ", pmaPptgC=" + pmaPptgC +
            ", secTyC=" + secTyC +
            ", prdtC=" + prdtC +
            ", symbC=" + symbC +
            ", prcMulrA=" + prcMulrA +
            ", coreFundI=" + coreFundI +
            ", coreFundC=" + coreFundC +
            ", trdDShtQ=" + trdDShtQ +
            ", setlDShtQ=" + setlDShtQ +
            ", adjD=" + adjD +
            ", adjAcnC=" + adjAcnC +
            ", adjRsnC=" + adjRsnC +
            ", fileRunD=" + fileRunD +
            ", fileAccSrcC=" + fileAccSrcC +
            ", insrTmst=" + insrTmst +
            ", runId=" + runId +
            ", origTdMkvlA=" + origTdMkvlA +
            ", origTdQtyA=" + origTdQtyA +
            ", accSrcC=" + accSrcC +
            ", runD=" + runD +
            "]";
    }
}
